name: autofix.ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npx prettier --write src/*
      - uses: autofix-ci/action@v1
        with:
          commit-message: 'Format code with Prettier'
